### ISSUE TITLE
Creating a PULL_REQUEST_TEMPLATE.md

### ISSUE THREAD

**Issue by 4darsh-Dev** [knight1001d/automarket#13]
## Creating a pull request template for the project to make this repository suitable for Github community standards. 

What will it have ?
1. Brief Description
2. Issue it addresses or closes 
3. Checklist for (tested locally, necessary documentation , etc.)
4. Screenshots and Additional notes

**Comment by sleathblack007** [comment]
I'm a beginner in Open Source having good theoretical knowledge  Do you think I can contribute to this project? If yes, I would be happy to learn and contribute!

**Comment by knight1001d** [comment]
Assigned to you @4darsh-Dev.

**Comment by 21atha** [comment]
I would like to work on this feature @knight1001d , please assign it to me.
