### ISSUE TITLE
Adding list of contributors image in readme

### ISSUE THREAD

**Issue by Arpcoder** [knight1001d/automarket#19]
**Describe the solution you'd like**
list of contributors image in readme

**Additional context**

![image](https://github.com/knight1001d/automarket/assets/100352419/8f098474-22a0-405e-b01a-ce369dff0346)

**Comment by knight1001d** [comment]
Great. Do you want to work on this issue? @Arpcoder

**Comment by Arpcoder** [comment]
> Great. Do you want to work on this issue? @Arpcoder

Yes, definitely

**Comment by Arpcoder** [comment]
@knight1001d please add gssoc and level labels to this issue

**Comment by knight1001d** [comment]
@Arpcoder added the labels.

**Comment by Arpcoder** [comment]
> @Arpcoder added the labels.

Thank you.
