### ISSUE TITLE
[Feat]: Workflow for closing Old PRs

### ISSUE THREAD

**Issue by Asymtode712** [knight1001d/automarket#25]
**Is your feature request related to a problem? Please describe.**
Over time, open pull requests (PRs) can accumulate in a repository, cluttering the interface and making it difficult to focus on active development tasks. Additionally, outdated or abandoned PRs may no longer serve their intended purpose and should be closed to maintain repository cleanliness.

**Describe the solution you'd like**
Implement a workflow that automatically closes old PRs based on predefined criteria, such as their last update timestamp. By regularly closing PRs that have not been updated within a certain timeframe, the repository can stay organized, and contributors can focus on active and relevant PRs.

**Additional context**

![Close Old PRs](https://github.com/knight1001d/automarket/assets/115717746/1dba8249-954e-4f8e-861b-4aaad444c8e3)

**Comment by knight1001d** [comment]
I dont think we need this right now. Closing. @Asymtode712
