### ISSUE TITLE
Bug: Issue in autocommenting merged pr:

### ISSUE THREAD

**Issue by Anshika14528** [knight1001d/automarket#29]
**Describe the bug**
I checked on the recent merged pr but we are not getting the autocomment feature and i looked more into it and i found this message
<img width="1451" alt="Screenshot 2024-05-27 at 11 49 20 PM" src="https://github.com/knight1001d/automarket/assets/168436423/f981522c-4b37-4a5c-8084-a77d2369870a">

**Additional context**
For the fix can you make sure you have these permissions on
<img width="675" alt="Screenshot 2024-05-27 at 3 03 30 PM" src="https://github.com/knight1001d/automarket/assets/168436423/fd881aa8-1d06-4634-a69e-824ef255a9fe">
and if it doesn't work please let me work on this

**Comment by knight1001d** [comment]
Sure. Assigning to you @Anshika14528

**Comment by knight1001d** [comment]
@Anshika14528 I have reopened the issue.

**Comment by Anshika14528** [comment]
@knight1001d  sir , i have created the new pr please review it and merge it
 sorry for the inconvenience
