### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by Princegupta101** [knight1001d/automarket#5]
We recommend that every repo has a code of conduct. If you don’t feel comfortable creating your own Code of Conduct from scratch we highly recommend using one of the templates provided by GitHub. If you do use a template, please read through the template and ensure that you can and will abide by the Code of Conduct.

Please follow these instructions on how to add a Code of Conduct.

Sample: https://github.com/Recode-Hive/Stackoverflow-Analysis/blob/main/CODE_OF_CONDUCT.md

**Comment by IP80808080** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Additionally, could you please label it for the appropriate level? Thank you! 🚀

**Comment by tupur-29** [comment]
I would like to work on this issue. Please assign this task to me

**Comment by SaiSruthisri** [comment]
Hello Iam a gssoc'24 contributir & would like to work on this issue ,kindly assign this task to me & please label it under appropriate level.
Than you!

**Comment by knight1001d** [comment]
@tupur-29 Assigned to you.

**Comment by knight1001d** [comment]
Resolved.
