### ISSUE TITLE
Update READ.md

### ISSUE THREAD

**Issue by aditi-sharma-2004** [knight1001d/automarket#8]
I would love to update the documentation. Please assign this issue to me under GSSOC'24.

**Comment by AnanyaSinghal23** [comment]
I would like to work on this issue under GSSOC, please assign it to me. Thank you.

**Comment by SaiSruthisri** [comment]
Hello @knight1001d 
I would like work on this please assign me task under gssoc'24.
Thank you.

**Comment by knight1001d** [comment]
@aditi-sharma-2004  You can work on this issue.

**Comment by Mooosiee** [comment]
could you please assign labels

**Comment by IP80808080** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Thank you! 🚀
I have just now have created a beautiful Learn.md (Link)[https://github.com/urstrulynishkarsh/ReactChat/blob/main/Learn.md] with Video as well

**Comment by knight1001d** [comment]
@aditi-sharma-2004 Hi Aditi, are you working on this, please confirm once.

**Comment by aasthakourav20** [comment]
Hey @knight1001d , this issue is still open . If not worked upon , Kindly assign it to  me under GSSoC'24 as for user/contributor 
convenience an enhanced and updated Readme file is important .

**Comment by knight1001d** [comment]
@aditi-sharma-2004 I'm unassigning this from you and assigning this to @aasthakourav20.
